baseURL = ""
languageCode = "en-us"
title = "Joan Perals"
theme = "cocoa"

[params]
avatar = "img/profile-color-transparent-bg.png"
projects_url = "https://perals.xyz"
linkedin_url = "https://linkedin.com/in/joanperalstresserra"
