baseURL: ""
languageCode: "en-us"
title: "Joan Perals — UX Developer"
googleAnalytics: "UA-7899353-3"

params:
    description: "Berlin-based web developer and creative technologist with 10 years of professional experience."
    avatar: "img/profile-color-transparent-bg.png"
    cv_url: "/cv-joanperals-2019.05.03_01.pdf"
    site_name: "perals.io"
    projects_url: "https://perals.io"
    linkedin_url: "https://linkedin.com/in/joanperalstresserra"

menu:
  main:
  - identifier: technical-skills
    name: Toolbox
    title: Toolbox
    url: /#technical-skills
    weight: 1
  - identifier: /projects
    name: Projects
    title: Projects
    url: /#projects
    weight: 2
  - identifier: professional-experience
    name: Professional experience
    title: Professional experience
    url: /#professional-experience
    weight: 3
  - identifier: contact
    name: Contact
    title: Contace
    url: /#contact
    weight: 4
  - identifier: blog
    name: Blog
    title: Blog
    url: /posts/
    weight: 5
  - identifier: cv
    name: CV
    title: CV
    url: /cv-joanperals-2019.05.03_01.pdf
    weight: 6
