baseURL = ""
languageCode = "en-us"
title = "Joan Perals — Web Developer, Creative Technologist, Digital Craftsman"
googleAnalytics = "UA-7899353-3"

[params]
description = "Berlin-based web developer and creative technologist with 10 years of professional experience."
avatar = "img/profile-color-transparent-bg.png"
cv_url = "/cv-joanperals-2019.05.03_01.pdf"
projects_url = "https://perals.io"
linkedin_url = "https://linkedin.com/in/joanperalstresserra"
