baseURL = ""
languageCode = "en-us"
title = "Joan Perals"
googleAnalytics = "UA-7899353-3"

[params]
avatar = "img/profile-color-transparent-bg.png"
projects_url = "https://perals.io"
linkedin_url = "https://linkedin.com/in/joanperalstresserra"
