baseURL = ""
languageCode = "en-us"
title = "Joan Perals"
description = "Berlin-based web developer and creative technologist with 10 years of professional experience."
googleAnalytics = "UA-7899353-3"

[params]
avatar = "img/profile-color-transparent-bg.png"
projects_url = "https://perals.io"
linkedin_url = "https://linkedin.com/in/joanperalstresserra"
